[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mood-mud"
version = "0.1.0"
description = "Multi-User Dungeon with cowsay and wandering monsters"
readme = "README.md"
authors = [{name = "Mishkasniper", email = "s02230115@gse.cs.msu.ru"}]
dependencies = [
    "python-cowsay>=1.0"
]
requires-python = ">=3.8"

[project.scripts]
mood-client = "mood.client.__main__:main"
mood-server = "mood.server.__main__:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["mood*"]

[tool.setuptools.package-data]
mood = [
    "server/locale/**/*.mo",
    "common/extra_monster.txt",
    "html_docs/**/*",
]

[dependency-groups]
devel = [
    "setuptools",
    "build",
    "doit",
    "babel",
    "sphinx",
    "pytest",
]